export const CATALOG_FILTERS_PRICE_LABEL = "Ціна, ₴";
export const CATALOG_FILTERS_PRICE_FROM_PLACEHOLDER = "від";
export const CATALOG_FILTERS_PRICE_TO_PLACEHOLDER = "до";
export const CATALOG_FILTERS_APPLY_LABEL = "Застосувати";
export const CATALOG_FILTERS_RESET_LABEL = "Скинути фільтри";
export const CATALOG_FILTERS_MORE_LABEL = "Показати ще";
export const CATALOG_FILTERS_AVAILABILITY_LABEL = "Наявність";
export const CATALOG_FILTERS_AVAILABLE_ONLY_LABEL = "Тільки в наявності";
export const CATALOG_FILTERS_VISIBLE_OPTIONS_COUNT = 4;
