import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Unbounded } from "next/font/google";
import localFont from "next/font/local";
import { BottomTabBar } from "./layouts/bottom-tab-bar/bottom-tab-bar";
import { Footer } from "./layouts/footer/footer";
import { Header } from "./layouts/header/header";
import { QueryProvider } from "./core/providers/query-provider/query-provider";
import { ToastProvider } from "./core/providers/toast-provider/toast-provider";
import { getCatalogCategoryTreeHelper } from "./shared/catalog-categories/helpers/get-catalog-category-tree";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const materialSymbolsOutlined = localFont({
  src: "./core/fonts/material-symbols-outlined.woff2",
  variable: "--font-material-symbols",
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const unbounded = Unbounded({
  variable: "--font-unbounded",
  subsets: ["latin"],
  weight: ["500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const categoryTree = await getCatalogCategoryTreeHelper();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${unbounded.variable} ${materialSymbolsOutlined.variable} h-full antialiased`}
    >
      <head>
        <title>Ocean Shop</title>
      </head>
      <body className="min-h-full flex flex-col pb-[78px] lg:pb-0">
        <ToastProvider>
          <QueryProvider>
            <Header />
            {/* Grows to fill short pages so the footer stays at the bottom of the viewport. */}
            <main className="flex flex-1 flex-col">{children}</main>
            <Footer />
            <BottomTabBar categories={categoryTree} />
          </QueryProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
